/* eslint-disable unused-imports/no-unused-vars */
export enum Placeholders {
  USERNAME = 'Please enter your username.',
  PASSWORD = 'Please enter your password.',
  LOREM_1 = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vestibulum luctus accumsan. Aenean accumsan finibus risus, sit amet tincidunt massa tristique eget. Nam euismod quis eros non laoreet. Nulla non felis lorem. Nulla sagittis at justo eu auctor. Aenean sem nibh, convallis in sem et, volutpat placerat neque. Fusce sodales luctus nibh ac gravida. Donec tristique orci id porttitor posuere. Aenean ut facilisis justo, id ultricies turpis.',
  LOREM_2 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vestibulum luctus accumsan. Aenean accumsan finibus risus, sit amet tincidunt massa tristique eget. Nam euismod quis eros non laoreet. Nulla non felis lorem. Nulla sagittis at justo eu auctor. Aenean sem nibh, convallis in sem et, volutpat placerat neque. Fusce sodales luctus nibh ac gravida. Donec tristique orci id porttitor posuere. Aenean ut facilisis justo, id ultricies turpis.

  Mauris accumsan pulvinar urna sed fermentum. Phasellus ut nisi convallis, ultricies orci vitae, pulvinar libero. Nulla id efficitur mauris, sit amet fringilla massa. Fusce suscipit sit amet nisi et euismod. Praesent consequat enim tempor nisi sodales rutrum. Sed mattis augue sed ullamcorper accumsan. Integer nulla enim, suscipit pellentesque nibh in, fringilla commodo neque. Nam in commodo mi, quis auctor orci. Morbi felis lorem, faucibus sed efficitur vel, sodales ac libero. Cras nisl dui, pretium nec augue a, porta luctus nisi.`,
  LOREM_3 = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vestibulum luctus accumsan. Aenean accumsan finibus risus, sit amet tincidunt massa tristique eget. Nam euismod quis eros non laoreet. Nulla non felis lorem. Nulla sagittis at justo eu auctor. Aenean sem nibh, convallis in sem et, volutpat placerat neque. Fusce sodales luctus nibh ac gravida. Donec tristique orci id porttitor posuere. Aenean ut facilisis justo, id ultricies turpis.

  Mauris accumsan pulvinar urna sed fermentum. Phasellus ut nisi convallis, ultricies orci vitae, pulvinar libero. Nulla id efficitur mauris, sit amet fringilla massa. Fusce suscipit sit amet nisi et euismod. Praesent consequat enim tempor nisi sodales rutrum. Sed mattis augue sed ullamcorper accumsan. Integer nulla enim, suscipit pellentesque nibh in, fringilla commodo neque. Nam in commodo mi, quis auctor orci. Morbi felis lorem, faucibus sed efficitur vel, sodales ac libero. Cras nisl dui, pretium nec augue a, porta luctus nisi.
  
  Aliquam at scelerisque massa. Nulla dapibus laoreet dui non egestas. In faucibus viverra lacus. Cras sit amet enim ac lacus dignissim sollicitudin quis vel odio. Donec ultrices rutrum nisi, nec bibendum quam dictum quis. Cras in mollis justo. Nullam quis erat pellentesque, tempus risus eget, pretium ipsum. Maecenas vitae dignissim dui, at dapibus nulla. Nunc hendrerit magna ut porta vehicula. Sed semper felis non dui facilisis feugiat ac id est. Integer lobortis varius dui eu placerat. Duis ac ante neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam nec risus pretium, lobortis justo eu, ultrices sapien.`,
}
